spring:
  # .env import
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver          # PostgreSQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: update                                # 스키마 자동 업데이트 (create, update, validate, none 등 선택)
    properties:
      hibernate:
        format_sql: true                              # SQL 포맷팅
    show-sql: true                                    # 실행되는 SQL 출력
  data:
    sql:
      enable: true                                    # data.sql 파일 사용 여부

# 로그 레벨 설정
logging:
  level:
    org.springframework: INFO                        # Spring 관련 로그 레벨
    org.hibernate.SQL: DEBUG                         # Hibernate SQL 로그 레벨