apiVersion: v1

kind: Pod

metadata:
  name: backend-pod
  labels:
    app: backend-app

spec:
  containers:
    - name: backend-container
      image: 323594814947.dkr.ecr.ap-northeast-2.amazonaws.com/k8s/backend-app:3.0.1
      ports:
        - containerPort: 8080