apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80        # 외부에서 접근할 포트
      targetPort: 8080 # 실제 컨테이너가 사용하는 포트